version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /srv/docker-state/nginx/conf.d:/etc/nginx/conf.d
      - /srv/docker-state/nginx/vhost.d:/etc/nginx/vhost.d
      - /srv/docker-state/nginx/html:/usr/share/nginx/html
      - /srv/nginx/certs:/etc/nginx/certs:ro
      - /srv/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
  
  wget:
    image: mwendler/wget
    container_name: wget
    volumes_from:
      - gen
    command: "--no-clobber --output-document /srv/nginx.tmpl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl"

  gen:
    image: jwilder/docker-gen
    container_name: gen
    command: "-notify-sighup nginx -watch -only-exposed -wait 5s:30s /srv/nginx.tmpl /etc/nginx/conf.d/default.conf"
    volumes_from: 
      - nginx
    volumes:
      - /srv/nginx.tmpl
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    labels:
      io.rancher.sidekicks: nginx, letsencrypt

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    depends_on: 
      - gen
    volumes_from: 
      - nginx
    volumes:
      - /srv/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=gen
    restart: always